# CircleCi Configuration for local_pathfinding

version: 2.1
jobs:
  test:
    docker:
      - image: tylerlum/ros_ompl_python_2:04.2020.V1
    steps:
      # Install circle ci dependencies
      - run: apt-get update && apt-get install -y git ssh tar gzip ca-certificates

      # Setup workspace and build code
      - run: mkdir -p /catkin_ws/src/local_pathfinding
      - run: source /opt/ros/melodic/setup.bash && cd /catkin_ws && catkin_make
      - checkout:
          path: /catkin_ws/src/local_pathfinding
      - run: source /opt/ros/melodic/setup.bash && cd /catkin_ws && catkin_make

      # Run tests and check results
      - run: source /opt/ros/melodic/setup.bash && source /catkin_ws/devel/setup.bash && cd /catkin_ws && catkin_make run_tests && catkin_test_results
